### ISSUE TITLE
specialization & delegation of provided interface => code generation seems incomplete

### ISSUE THREAD

**Issue by erikmd** [victornoel/may#1]
Hi Victor,
It seems that code generation is incomplete with MAY 3.5.1.201702131720, when a component (say, Print2) **specializes** another component (say, Print) and introduces a "delegation connector" for a **provides** port.

I thought this kind of situation was OK since f89925e, but it seems that it doesn't.
Below is a minimal working example:
### interfaces/IPrint.java
```java
package interfaces;
public interface IPrint {
	void print(String message);
}
```
### proxy.speadl
```
import interfaces.IPrint
namespace proxy {
	component Print {
		provides print : IPrint
	}
	component Proxy {
		provides in : IPrint
		requires out : IPrint
	}
	component Print2 specializes Print {
		provides print : IPrint = proxy.in
		part proxy : Proxy {
			bind out to reuse.print
		}
		part reuse : Print
	}
}
```
### proxy/PrintImplem.java
```java
package proxy;
import interfaces.IPrint;
public class PrintImplem extends Print implements IPrint {
	@Override
	protected IPrint make_print() {
		return this;
	}
	@Override
	public void print(String message) {
		System.out.println(message);
	}
}
```
### proxy/ProxyImplem.java
```java
package proxy;
import interfaces.IPrint;
public class ProxyImplem extends Proxy implements IPrint {
	@Override
	protected IPrint make_in() {
		return this;
	}
	@Override
	public void print(String message) {
		requires().out().print("[Print2]" + message);
	}
}
```
### proxy/Print2Implem.java
```java
package proxy;
import interfaces.IPrint;
public class Print2Implem extends Print2 {
	@Override
	protected Print make_reuse() {
		return new PrintImplem();
	}
	@Override
	protected Proxy make_proxy() {
		return new ProxyImplem();
	}
	/* FIXME Should be unnecessary / automatically generated */
	@Override
	protected IPrint make_print() { return parts().proxy().in(); }
}
```
Kind regards.

**Comment by victornoel** [comment]
Ok, so I found where the error lies!
Actually `make_print()` is never called, so even if you put nothing in it, it would work.

I pushed a commit to generate an empty implementation in the overriding class. It shouldn't impact may-lib.

@erikmd could you try the latest snapshot (3.5.1 from http://victornoel.github.io/may/update-may-3-snapshots/) with your code and also with your other teaching materials in order to be sure it didn't introduce regressions? Just do a `Project->Clean` from the menus to trigger regeneration.

Thanks again :)
